In [1]:
import pyspark.sql.functions as F

In [2]:
def show (df,n):
    from IPython import display
    display.display(df.limit(n).toPandas())

In [3]:
conv_path = '/Users/IsabelGontijo/git/covid-19/refined/data/01_conversion/'

In [4]:
df = spark.read.csv(conv_path, header=True, multiLine=True)

In [5]:
for i,col in enumerate(df.columns):
    print(f'{i+1}/{len(df.columns)}')
    df.groupBy(col).count().orderBy(col).show(30, False)

1/12
+--------+-----+
|epi_week|count|
+--------+-----+
|10      |27   |
|101     |39172|
|102     |39172|
|103     |39172|
|104     |39172|
|105     |39172|
|106     |39172|
|107     |39172|
|108     |39172|
|109     |39172|
|11      |138  |
|110     |39172|
|111     |39172|
|112     |39172|
|113     |39172|
|114     |39172|
|115     |39172|
|116     |39172|
|117     |39172|
|118     |39172|
|119     |39172|
|12      |575  |
|120     |39172|
|121     |39172|
|122     |39172|
|123     |39172|
|124     |39172|
|125     |39177|
|126     |39179|
|127     |39179|
+--------+-----+
only showing top 30 rows

2/12
+----------+-----+
|date      |count|
+----------+-----+
|2020-02-25|2    |
|2020-02-26|2    |
|2020-02-27|2    |
|2020-02-28|2    |
|2020-02-29|2    |
|2020-03-01|2    |
|2020-03-02|2    |
|2020-03-03|2    |
|2020-03-04|2    |
|2020-03-05|3    |
|2020-03-06|7    |
|2020-03-07|9    |
|2020-03-08|11   |
|2020-03-09|11   |
|2020-03-10|13   |
|2020-03-11|14   |
|2020-03-12|25   |
|2020-03-13|28   |
|2020-03-14|36   |
|2020-03-15|36   |
|2020-03-16|45   |
|2020-03-17|58   |
|2020-03-18|76   |
|2020-03-19|94   |
|2020-03-20|121  |
|2020-03-21|145  |
|2020-03-22|157  |
|2020-03-23|184  |
|2020-03-24|203  |
|2020-03-25|233  |
+----------+-----+
only showing top 30 rows

3/12
+-----+------+
|state|count |
+-----+------+
|AC   |14388 |
|AL   |63748 |
|AM   |39921 |
|AP   |10779 |
|BA   |256074|
|CE   |117302|
|DF   |677   |
|ES   |50368 |
|GO   |148005|
|MA   |134997|
|MG   |510856|
|MS   |48352 |
|MT   |85764 |
|PA   |91300 |
|PB   |136751|
|PE   |117051|
|PI   |135650|
|PR   |242141|
|RJ   |59825 |
|RN   |103815|
|RO   |32728 |
|RR   |10145 |
|RS   |298122|
|SC   |182000|
|SE   |47191 |
|SP   |400370|
|TO   |85332 |
|TOTAL|688   |
+-----+------+

4/12
+----------------------+-----+
|city                  |count|
+----------------------+-----+
|ABADIA DE GOIAS/GO    |602  |
|ABADIA DOS DOURADOS/MG|615  |
|ABADIANIA/GO          |594  |
|ABAETE/MG             |641  |
|ABAETETUBA/PA         |653  |
|ABAIARA/CE            |626  |
|ABAIRA/BA             |640  |
|ABARE/BA              |608  |
|ABATIA/PR             |615  |
|ABDON BATISTA/SC      |594  |
|ABEL FIGUEIREDO/PA    |616  |
|ABELARDO LUZ/SC       |612  |
|ABRE CAMPO/MG         |584  |
|ABREU E LIMA/PE       |644  |
|ABREULANDIA/TO        |618  |
|ACAIACA/MG            |574  |
|ACAILANDIA/MA         |652  |
|ACAJUTIBA/BA          |631  |
|ACARA/PA              |642  |
|ACARAPE/CE            |635  |
|ACARAU/CE             |636  |
|ACARI/RN              |640  |
|ACAUA/PI              |589  |
|ACEGUA/RS             |546  |
|ACOPIARA/CE           |640  |
|ACORIZAL/MT           |613  |
|ACRELANDIA/AC         |655  |
|ACREUNA/GO            |591  |
|ACU/RN                |656  |
|ACUCENA/MG            |604  |
+----------------------+-----+
only showing top 30 rows

5/12
+-------+-----+
|ibgeID |count|
+-------+-----+
|0      |688  |
|11     |629  |
|1100015|621  |
|1100023|643  |
|1100031|621  |
|1100049|623  |
|1100056|601  |
|1100064|586  |
|1100072|586  |
|1100080|599  |
|1100098|622  |
|1100106|623  |
|1100114|654  |
|1100122|664  |
|1100130|619  |
|1100148|617  |
|1100155|645  |
|1100189|632  |
|1100205|663  |
|1100254|611  |
|1100262|606  |
|1100288|648  |
|1100296|608  |
|1100304|648  |
|1100320|611  |
|1100338|611  |
|1100346|617  |
|1100379|619  |
|1100403|635  |
|1100452|637  |
+-------+-----+
only showing top 30 rows

6/12
+---------+-----+
|newDeaths|count|
+---------+-----+
|-1       |6577 |
|-10      |31   |
|-105     |1    |
|-109     |1    |
|-11      |27   |
|-111     |2    |
|-112     |1    |
|-113     |1    |
|-114     |1    |
|-117     |1    |
|-119     |1    |
|-12      |15   |
|-122     |1    |
|-123     |1    |
|-124     |1    |
|-125     |1    |
|-126     |1    |
|-129     |1    |
|-13      |18   |
|-130     |2    |
|-1303    |1    |
|-132     |2    |
|-133     |1    |
|-14      |21   |
|-140     |1    |
|-141     |1    |
|-15      |17   |
|-150     |1    |
|-154     |1    |
|-157     |1    |
+---------+-----+
only showing top 30 rows

7/12
+------+------+
|deaths|count |
+------+------+
|0     |453284|
|1     |280578|
|10    |81125 |
|100   |2299  |
|1000  |8     |
|10007 |1     |
|1001  |19    |
|10012 |1     |
|1002  |22    |
|10024 |1     |
|10027 |2     |
|1003  |21    |
|1004  |7     |
|10041 |1     |
|1005  |21    |
|10053 |1     |
|10054 |1     |
|1006  |29    |
|10062 |1     |
|100657|1     |
|1007  |24    |
|10074 |1     |
|1008  |23    |
|10084 |1     |
|10085 |1     |
|1009  |16    |
|10099 |1     |
|101   |2407  |
|1010  |29    |
|10104 |1     |
+------+------+
only showing top 30 rows

8/12
+--------+-----+
|newCases|count|
+--------+-----+
|-1      |27929|
|-10     |233  |
|-100    |9    |
|-1000   |2    |
|-1002   |1    |
|-10035  |1    |
|-1004   |1    |
|-1006   |1    |
|-1009   |1    |
|-10099  |1    |
|-101    |3    |
|-1010   |2    |
|-1012   |1    |
|-1013   |1    |
|-1016   |1    |
|-1017   |1    |
|-1018   |2    |
|-102    |3    |
|-1020   |1    |
|-1022   |1    |
|-1025   |2    |
|-1026   |1    |
|-103    |9    |
|-10330  |1    |
|-1034   |1    |
|-1038   |1    |
|-104    |2    |
|-1042   |2    |
|-1047   |2    |
|-10498  |1    |
+--------+-----+
only showing top 30 rows

9/12
+----------+-----+
|totalCases|count|
+----------+-----+
|0         |23547|
|1         |57969|
|10        |11808|
|100       |3981 |
|1000      |738  |
|10000     |12   |
|10001     |10   |
|100011    |1    |
|100012    |1    |
|10002     |25   |
|10003     |18   |
|100031    |1    |
|100032    |1    |
|10004     |57   |
|100044    |1    |
|100045    |1    |
|100047    |1    |
|10005     |10   |
|100057    |1    |
|10006     |8    |
|10007     |28   |
|100071    |1    |
|10008     |17   |
|10009     |9    |
|100090    |1    |
|1001      |1010 |
|10010     |12   |
|100107    |1    |
|100109    |1    |
|10011     |49   |
+----------+-----+
only showing top 30 rows

10/12
+---------------------------+------+
|deaths_per_100k_inhabitants|count |
+---------------------------+------+
|0.000                      |453285|
|0.002                      |7     |
|0.003                      |1     |
|0.005                      |2     |
|0.006                      |3     |
|0.007                      |16    |
|0.008                      |2     |
|0.009                      |7     |
|0.010                      |35    |
|0.011                      |13    |
|0.012                      |12    |
|0.013                      |25    |
|0.014                      |40    |
|0.015                      |1     |
|0.016                      |1     |
|0.017                      |15    |
|0.020                      |7     |
|0.021                      |2     |
|0.022                      |8     |
|0.023                      |8     |
|0.024                      |14    |
|0.025                      |40    |
|0.026                      |24    |
|0.027                      |17    |
|0.028                      |12    |
|0.029                      |54    |
|0.030                      |5     |
|0.031                      |13    |
|0.032                      |1     |
|0.033                      |3     |
+---------------------------+------+
only showing top 30 rows

11/12
+-------------------------------+-----+
|totalCases_per_100k_inhabitants|count|
+-------------------------------+-----+
|0.000                          |23550|
|0.001                          |6    |
|0.003                          |1    |
|0.006                          |20   |
|0.007                          |1    |
|0.008                          |3    |
|0.009                          |15   |
|0.010                          |4    |
|0.011                          |3    |
|0.012                          |8    |
|0.014                          |30   |
|0.015                          |5    |
|0.016                          |6    |
|0.018                          |3    |
|0.020                          |2    |
|0.021                          |1    |
|0.022                          |4    |
|0.023                          |4    |
|0.024                          |4    |
|0.025                          |22   |
|0.028                          |8    |
|0.029                          |6    |
|0.030                          |4    |
|0.031                          |3    |
|0.032                          |4    |
|0.033                          |1    |
|0.035                          |8    |
|0.040                          |1    |
|0.041                          |11   |
|0.042                          |5    |
+-------------------------------+-----+
only showing top 30 rows

12/12

+--------------------+------+
|deaths_by_totalCases|count |
+--------------------+------+
|0.000               |453401|
|0.001               |1058  |
|0.002               |6803  |
|0.003               |15529 |
|0.004               |25749 |
|0.005               |34843 |
|0.006               |42919 |
|0.007               |49607 |
|0.008               |59228 |
|0.009               |64392 |
|0.010               |72718 |
|0.011               |82697 |
|0.012               |87873 |
|0.013               |93285 |
|0.014               |101237|
|0.015               |102038|
|0.016               |101504|
|0.017               |107073|
|0.018               |103489|
|0.019               |104375|
|0.020               |101659|
|0.021               |96587 |
|0.022               |94848 |
|0.023               |86201 |
|0.024               |87245 |
|0.025               |81174 |
|0.026               |76311 |
|0.027               |68328 |
|0.028               |63902 |
|0.029               |66281 |
+--------------------+------+
only showing top 30 rows

In [6]:
if sc: sc.stop()